"""API v1 schemas."""

from mgmt_server.api.v1.schemas.auth import LoginRequest, LoginResponse, TokenVerifyResponse
from mgmt_server.api.v1.schemas.base import BaseResponse
from mgmt_server.api.v1.schemas.repos import (
    CreateTaskFromCacheRequest,
    CreateTaskFromPreviewRequest,
    CreateTaskRequest,
    DryRunRequest,
    RepoItem,
    RepoDetailResponse,
    RepoDetailData,
    RepoListResponse,
    RepoProfileResponse,
    RepoSnapshotResponse,
)
from mgmt_server.api.v1.schemas.configs import (
    ConfigItem,
    ConfigCreateRequest,
    ConfigUpdateRequest,
    ConfigBatchUpdateRequest,
    ConfigListResponse,
    ConfigDetailResponse,
    SMTPConfigResponse,
)
from mgmt_server.api.v1.schemas.tasks import (
    AsyncPreviewTaskData,
    AsyncPreviewTaskResponse,
    AsyncPreviewTaskStatusData,
    AsyncPreviewTaskStatusResponse,
    PreviewItem,
    TaskCreatorUser,
    TaskResponse,
    TaskListResponse,
    TaskDetailResponse,
    TaskPreviewData,
    TaskPreviewRequest,
    TaskPreviewResponse,
    TaskReviewRequest,
)
from mgmt_server.api.v1.schemas.progress import (
    FileProgressItem,
    TaskProgressData,
    TaskProgressResponse,
)

__all__ = [
    "BaseResponse",
    "LoginRequest",
    "LoginResponse",
    "TokenVerifyResponse",
    "CreateTaskFromCacheRequest",
    "CreateTaskFromPreviewRequest",
    "CreateTaskRequest",
    "DryRunRequest",
    "RepoItem",
    "RepoDetailResponse",
    "RepoDetailData",
    "RepoListResponse",
    "RepoProfileResponse",
    "RepoSnapshotResponse",
    "ConfigItem",
    "ConfigCreateRequest",
    "ConfigUpdateRequest",
    "ConfigBatchUpdateRequest",
    "ConfigListResponse",
    "ConfigDetailResponse",
    "SMTPConfigResponse",
    "AsyncPreviewTaskData",
    "AsyncPreviewTaskResponse",
    "AsyncPreviewTaskStatusData",
    "AsyncPreviewTaskStatusResponse",
    "PreviewItem",
    "TaskCreatorUser",
    "TaskResponse",
    "TaskListResponse",
    "TaskDetailResponse",
    "TaskPreviewData",
    "TaskPreviewRequest",
    "TaskPreviewResponse",
    "TaskReviewRequest",
    "FileProgressItem",
    "TaskProgressData",
    "TaskProgressResponse",
]
