"""API v1 schemas."""

from mgmt_server.api.v1.schemas.auth import (
    LoginResponse,
    RefreshTokenResponse,
    TokenData,
    RegisterWithCodeRequest,
    SendVerifyCodeRequest,
    SendVerifyCodeResponse,
    TokenVerifyResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
)
from mgmt_server.api.v1.schemas.base import BaseResponse, PaginationQueryParams
from mgmt_server.api.v1.schemas.configs import (
    AnnouncementConfigResponse,
    AnnouncementSaveRequest,
    ConfigBatchUpdateRequest,
    ConfigCreateRequest,
    ConfigDeleteResponse,
    ConfigDetailResponse,
    ConfigItem,
    ConfigListResponse,
    ConfigUpdateRequest,
    HFEndpointConfigResponse,
    HFEndpointSaveRequest,
    NotificationConfigResponse,
    NotificationSaveRequest,
    SMTPConfigResponse,
    SMTPSaveRequest,
    SMTPTestRequest,
    SMTPTestResponse,
)
from mgmt_server.api.v1.schemas.progress import (
    FileProgressItem,
    TaskProgressData,
    TaskProgressResponse,
)
from mgmt_server.api.v1.schemas.repos import (
    CreateTaskFromCacheRequest,
    CreateTaskFromPreviewRequest,
    DashboardStatsResponse,
    DeleteRepoResponse,
    DeleteRepoResult,
    RepoDetailResponse,
    RepoFileItem,
    RepoListQueryParams,
    RepoListResponse,
    RepoTreeResponse,
)
from mgmt_server.api.v1.schemas.tasks import (
    ActiveTaskListResponse,
    AsyncPreviewTaskData,
    AsyncPreviewTaskResponse,
    AsyncPreviewTaskStatusData,
    AsyncPreviewTaskStatusResponse,
    PublicTaskListQueryParams,
    TaskCreatorUser,
    TaskDetailResponse,
    TaskListQueryParams,
    TaskListResponse,
    TaskPreviewData,
    TaskPreviewRequest,
    TaskResponse,
    TaskReviewRequest,
)

__all__ = [
    "BaseResponse",
    "PaginationQueryParams",
    # auth
    "LoginResponse",
    "RefreshTokenResponse",
    "TokenData",
    "RegisterWithCodeRequest",
    "SendVerifyCodeRequest",
    "SendVerifyCodeResponse",
    "TokenVerifyResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    # repos
    "CreateTaskFromCacheRequest",
    "CreateTaskFromPreviewRequest",
    "DashboardStatsResponse",
    "DeleteRepoResponse",
    "DeleteRepoResult",
    "RepoDetailResponse",
    "RepoFileItem",
    "RepoListQueryParams",
    "RepoListResponse",
    "RepoTreeResponse",
    # configs
    "AnnouncementConfigResponse",
    "AnnouncementSaveRequest",
    "ConfigBatchUpdateRequest",
    "ConfigCreateRequest",
    "ConfigDeleteResponse",
    "ConfigDetailResponse",
    "ConfigItem",
    "ConfigListResponse",
    "ConfigUpdateRequest",
    "HFEndpointConfigResponse",
    "HFEndpointSaveRequest",
    "NotificationConfigResponse",
    "NotificationSaveRequest",
    "SMTPConfigResponse",
    "SMTPSaveRequest",
    "SMTPTestRequest",
    "SMTPTestResponse",
    # progress
    "FileProgressItem",
    "TaskProgressData",
    "TaskProgressResponse",
    # tasks
    "ActiveTaskListResponse",
    "AsyncPreviewTaskData",
    "AsyncPreviewTaskResponse",
    "AsyncPreviewTaskStatusData",
    "AsyncPreviewTaskStatusResponse",
    "PublicTaskListQueryParams",
    "TaskCreatorUser",
    "TaskDetailResponse",
    "TaskListQueryParams",
    "TaskListResponse",
    "TaskPreviewData",
    "TaskPreviewRequest",
    "TaskResponse",
    "TaskReviewRequest",
]
